### ISSUE TITLE
ismart快捷方式无法修改

### ISSUE THREAD

**Issue by XGK666** [Mufanc/iSmartAuto2#17]
hi，你好。之前在别的地方看到你发的ismart答案，随后跟随你来到github。前几步我都照做了没有什么问题，但到了修改快捷方式这部，系统显示“请确定路径名和文件名是否正确”。不知道你能否看到这张图片。期待你的回复，谢谢！
<img width="418" alt="1" src="https://user-images.githubusercontent.com/100862977/156741292-80b311fc-0843-4d29-8ac7-fad3b1f1ac4d.png">
。

**Comment by Mufanc** [comment]
`D:\ismart\iSmart\client\iSmart.exe  --remote-debugging-port=9222`
注意空格
