### ISSUE TITLE
请问能不能按照章节来刷

### ISSUE THREAD

**Issue by anappl151** [Mufanc/iSmartAuto2#19]
请问能不能按照章节来刷，现在测试的是，带锁的章节也是一键完成的，这样如果老师那边看到就会出问题了😂所以问问这个问题   再一个就是刷完的可不可以再手动清除做题记录  谢谢博主

**Comment by Mufanc** [comment]
@anappl151 目前不支持按章节刷课；此外由于 API 限制，无法清除做题记录
