### ISSUE TITLE
显示填写账号和密码与登录不符

### ISSUE THREAD

**Issue by 1634222787** [Mufanc/iSmartAuto2#5]
![image](https://user-images.githubusercontent.com/47652878/139519267-c1ed9402-09b1-445c-9003-1e46b5650795.png)
我正确的填写了账号和密码运行时出现如上错误
恳求指点
后续可以在telegram上交流 @tasikaio

**Comment by Mufanc** [comment]
使用 `python main.py -vv list -d` 看一下详细日志

**Comment by dancemonkeyl** [comment]
请问这个怎么解决了呢最后

**Comment by dancemonkeyl** [comment]
这是个问题该怎么修改呢作者大人，我修改的是configs·yml里面删了那个用户名和密码，改了我的ismart上的密码和用户名，这个操作对吧！然后就出现和上面一样的问题

**Comment by Mufanc** [comment]
clone 一下最新的代码，然后查看详细日志

**Comment by hello2999** [comment]
> 这是个问题该怎么修改呢作者大人，我修改的是configs·yml里面删了那个用户名和密码，改了我的ismart上的密码和用户名，这个操作对吧！然后就出现和上面一样的问题

还要把<>删掉。
