### ISSUE TITLE
运行后正常，指令输入十几分钟后还是闪烁等待

### ISSUE THREAD

**Issue by dancemonkeyl** [Mufanc/iSmartAuto2#9]
一般这个是在刷还是卡了

**Comment by Mufanc** [comment]
正常刷课只要一分钟左右就可以结束

**Comment by dancemonkeyl** [comment]
请问那这是什么原因呢，应该在哪查看呢

**Comment by Mufanc** [comment]
原因并不好确定，如果你有 Python 开发基础，可以跟着 debug 走一趟

**Comment by dancemonkeyl** [comment]
可惜了，还不是很了解，才学到java，，，其他功能都正常如查课程，就是py main·py flash -c后，指针机会一直闪烁，然后就没有然后了

**Comment by Etongxue** [comment]
账号密码一直错误什么原因？

**Comment by dancemonkeyl** [comment]
把这个代码重新clone一份，再试试，我这样试了好了，但是就是有点点问题，搞不出来

**Comment by Etongxue** [comment]
试了还是不行，填写格式是什么，需不需要<>这个符号

**Comment by Etongxue** [comment]
open-python 4.5.36 怎么无法安装

**Comment by Etongxue** [comment]
和编译器没关系吧，我用的是vscode

**Comment by Etongxue** [comment]
和编译器没关系吧，我用的是vscode

**Comment by dancemonkeyl** [comment]
突然发现我的也是账号不匹配

**Comment by Mufanc** [comment]
我只有一个账号用于测试，而且只学视听说的课程，代码中难免会有疏漏
* 用户名密码不需要两边的尖括号，如果报密码错，建议用手机号登录试试
* 「账号不匹配」问题可以参考日志中标记的行，看看服务器返回的是怎样的数据
